<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Mengubah FK pengumuman.user_id dari CASCADE DELETE menjadi SET NULL.
     *
     * Sebelumnya: hapus user → semua pengumuman yang ia buat IKUT TERHAPUS.
     * Setelah fix: hapus user → pengumuman tetap ada, user_id menjadi null.
     */
    public function up(): void
    {
        Schema::table('pengumuman', function (Blueprint $table) {
            // 1. Drop FK lama (constraint name generated by Laravel: pengumuman_user_id_foreign)
            $table->dropForeign(['user_id']);

            // 2. Buat user_id nullable — syarat agar SET NULL bisa bekerja
            $table->unsignedBigInteger('user_id')->nullable()->change();

            // 3. Re-create FK dengan onDelete SET NULL
            $table->foreign('user_id')
                ->references('id')
                ->on('users')
                ->onDelete('set null');
        });
    }

    public function down(): void
    {
        Schema::table('pengumuman', function (Blueprint $table) {
            $table->dropForeign(['user_id']);

            // Revert ke non-nullable dengan CASCADE DELETE
            $table->unsignedBigInteger('user_id')->nullable(false)->change();

            $table->foreign('user_id')
                ->references('id')
                ->on('users')
                ->onDelete('cascade');
        });
    }
};
